Repository Spandan-Bhattacharya/Solve_it, pull requests merged in 2024-02, with the labels that each got.

#185 reset color problem fixed
  javascript/sudoku_solver4.js
  javascript/sudoku_solver6.js
  javascript/sudoku_solver9.js
Labels: easy, JWOC

#190 [ISSUE - 183] Enhance UI of the number solver and make it responsive
  css_files/number_solver.css
  html_files/numbersolver.html
  javascript/number_solver.js
Labels: hard, JWOC

#193 8 Puzzle Solver Added
  css_files/_8_puzzle.css
  html_files/_8_puzzle.html
  index.html
  javascript/_8_puzzle.js
Labels: hard, JWOC

#194 Added N-Queen Problem Solver
  css_files/queens.css
  html_files/queens.html
  index.html
  javascript/queens.js
Labels: hard, JWOC

#195 Added 4X4 sudoku validator
  .DS_Store
  html_files/sudoku_solver_4x4.html
  javascript/sudoku_solver4.js
Labels: hard, JWOC

#202 Changed the color palette of Number Solver to theme colors
  css_files/number_solver.css
  html_files/numbersolver.html
Labels: easy, JWOC

#205 Made the Navbar for pages responsive with Hamburger
  css_files/contributors.css
  css_files/newContact.css
  html_files/contributors.html
  html_files/newContact.html
Labels: hard, JWOC

#207 Resolving word unjumbler bug
  javascript/wordsolver.js
Labels: medium, JWOC

#225 Added back-to-home button
  css_files/wordsolver.css
  html_files/wordsolver.html
  javascript/wordsolver.js
Labels: easy, JWOC

#226 Applied linear gradient to the bg of Hamburger inset so that it match…
  css_files/styles.css
Labels: medium, JWOC

#228 Fix issue 223
  css_files/_8_puzzle.css
  css_files/styles.css
Labels: easy, JWOC

#229 Fixed the faq page
  css_files/faq.css
  html_files/faq.html
Labels: hard, JWOC

#231 Improve the 4x4 sudoku solver
  css_files/sudoku_solver4.css
  html_files/sudoku_solver_4x4.html
  javascript/sudoku_solver4.js
Labels: hard, JWOC

#230 Improved 8x8 suduku solver
  css_files/sudoku_solver8.css
  html_files/sudoku_solver_8x8.html
  javascript/sudoku_solver8.js
Labels: hard, JWOC

#232 Improved 9x9 Solver UI
  css_files/sudoku_solver9.css
  html_files/sudoku_solver_9x9.html
  javascript/sudoku_solver9.js
Labels: hard, JWOC

#235 Bug fixes on the home page
  css_files/styles.css
  html_files/toh.html
  index.html
Labels: easy, JWOC

#238 Improved Search Bar
  index.html
  javascript/autocomplete.js
Labels: hard, JWOC

#240 Improved Tower Of Hanoi
  css_files/toh.css
  html_files/toh.html
Labels: hard, JWOC

#242 Improved UI of N Queens Solver
  css_files/queens.css
  html_files/queens.html
  javascript/queens.js
Labels: hard, JWOC

#246 Changed In Home Page
  css_files/styles.css
  index.html
Labels: hard, JWOC

#253 Added Simon Game
  Simon Game/index.html
  Simon Game/script.js
  Simon Game/sounds/blue.mp3
  Simon Game/sounds/green.mp3
  Simon Game/sounds/red.mp3
  Simon Game/sounds/wrong.mp3
  Simon Game/sounds/yellow.mp3
  Simon Game/styles.css
  index.html
Labels: hard, JWOC

#251 Added 4x4 Sudoku Game
  css_files/sudocu_game_4x4.css
  html_files/sudoku_game_4x4.html
  index.html
  javascript/sudocu_game_4x4.js
Labels: hard, JWOC

#256 Add 8 x 8 Sudoku Game
  Sudoku_Game_8x8/index.html
  Sudoku_Game_8x8/script.js
  Sudoku_Game_8x8/style.css
  index.html
Labels: hard, JWOC

#261 Added 9x9 Sudoku Game
  Sudoku_Game_9x9/index.html
  Sudoku_Game_9x9/script.js
  Sudoku_Game_9x9/style.css
  index.html
Labels: hard, JWOC

#259 Added Checker Game
  css_files/checkers_game.css
  html_files/checkers_game.html
  index.html
  javascript/checkers_game.js
Labels: hard, JWOC

#263 Added 8 Puzzle Game
  css_files/_8_Puzzle_game.css
  html_files/_8_Puzzle_game.html
  index.html
  javascript/_8_Puzzle_game.js
Labels: hard, JWOC

#267 Added Connect 4 Game
  css_files/connect4.css
  html_files/Connect4.html
  index.html
  javascript/connect4.js
Labels: hard, JWOC

#274 Added Rock Paper Scissors Game !
  Rock Paper Scissor/images/paper.png
  Rock Paper Scissor/images/rock.png
  Rock Paper Scissor/images/scissor.png
  Rock Paper Scissor/index.html
  Rock Paper Scissor/script.js
  Rock Paper Scissor/style.css
  index.html
Labels: hard, JWOC

#277 Improved Input System of 8 Puzzle
  css_files/_8_puzzle.css
  html_files/_8_puzzle.html
  javascript/_8_puzzle.js
Labels: hard, JWOC

#280 Added Snake Game
  Snake Game/index.html
  Snake Game/script.js
  Snake Game/style.css
  index.html
Labels: hard, JWOC

#286 Improve 8 puzzle solver.
  javascript/_8_puzzle.js
Labels: medium, JWOC

#292 Improved Snake Game
  Snake Game/index.html
  Snake Game/script.js
  Snake Game/style.css
Labels: medium, JWOC

#290 Added Tetris Game
  Tetris/app.js
  Tetris/index.html
  Tetris/style.css
  index.html
Labels: hard, JWOC

#301 Added Sorting Visualizer !
  Sorting Visualizer/index.html
  Sorting Visualizer/script.js
  Sorting Visualizer/style.css
  index.html
Labels: hard, JWOC

#294 new game Word Guessing Game #284
  Word/index.html
  Word/script.js
  Word/style.css
  Word/word.js
  index.html
Labels: hard, JWOC

#297 Added navbar and footer to all the games pages
  2048/index.html
  2048/style.css
  CrossWord/index.html
  CrossWord/style.css
  HangMan Game/index.html
  HangMan Game/style.css
  Rock Paper Scissor/index.html
  Rock Paper Scissor/style.css
  Simon Game/index.html
  Simon Game/styles.css
  Snake Game/index.html
  Snake Game/style.css
  Sudoku_Game_8x8/index.html
  Sudoku_Game_8x8/style.css
  Sudoku_Game_9x9/index.html
  Sudoku_Game_9x9/style.css
  Tetris/index.html
  Tetris/style.css
  Tic-Tac-Toe/index.html
  Tic-Tac-Toe/style.css
  UNO/css/style.css
  UNO/index.html
  Word Scramble/index.html
  Word Scramble/style.css
  css_files/_8_Puzzle_game.css
  css_files/checkers_game.css
  css_files/connect4.css
  css_files/sudocu_game_4x4.css
  css_files/sudoku_game_6x6.css
  html_files/Connect4.html
  html_files/_8_Puzzle_game.html
  html_files/checkers_game.html
  html_files/sudoku_game_4x4.html
  html_files/sudoku_game_6x6.html
Labels: hard, JWOC

#308 Added navbar and footer to all the puzzle pages
  Sorting Visualizer/index.html
  Sorting Visualizer/style.css
  css_files/_8_puzzle.css
  css_files/number_solver.css
  css_files/queens.css
  css_files/sudoku_solver4.css
  css_files/sudoku_solver6.css
  css_files/sudoku_solver8.css
  css_files/sudoku_solver9.css
  css_files/toh.css
  css_files/wordsolver.css
  html_files/_8_puzzle.html
  html_files/numbersolver.html
  html_files/queens.html
  html_files/sudoku_solver_4x4.html
  html_files/sudoku_solver_6x6.html
  html_files/sudoku_solver_8x8.html
  html_files/sudoku_solver_9x9.html
  html_files/toh.html
  html_files/wordsolver.html
Labels: hard, JWOC

#310 Added Memory Card Game
  Memory Card game/images/img-1.png
  Memory Card game/images/img-2.png
  Memory Card game/images/img-3.png
  Memory Card game/images/img-4.png
  Memory Card game/images/img-5.png
  Memory Card game/images/img-6.png
  Memory Card game/images/img-7.png
  Memory Card game/images/img-8.png
  Memory Card game/index.html
  Memory Card game/script.js
  Memory Card game/style.css
  index.html
Labels: hard, JWOC

#302 Improved Search function and UI
  css_files/newContact.css
  html_files/newContact.html
  index.html
  javascript/autocomplete.js
Labels: hard, JWOC

#314 Added Bingo Game
  Bingo Game/app.js
  Bingo Game/index.html
  Bingo Game/style.css
  index.html
  javascript/autocomplete.js
Labels: hard, JWOC

#312 add new game Rubiks-cube #309
  Rubiks-Cube/bg.webp
  Rubiks-Cube/image.png
  Rubiks-Cube/index.html
  Rubiks-Cube/script.js
  Rubiks-Cube/style.css
  index.html
Labels: easy, JWOC

#324 Added Instruction tab for all game
  2048/index.html
  Bingo Game/index.html
  Bingo Game/style.css
  Block-Buster/index.html
  Block-Buster/styles.css
  CrossWord/index.html
  HangMan Game/index.html
  Memory Card game/index.html
  Memory Card game/style.css
  Ping_Pong/index.html
  Ping_Pong/style.css
  Rock Paper Scissor/index.html
  Simon Game/index.html
  Snake Game/index.html
  Sudoku_Game_8x8/index.html
  Sudoku_Game_9x9/index.html
  Tetris/index.html
  Tic-Tac-Toe/index.html
  UNO/index.html
  Word Scramble/index.html
  css_files/checkers_game.css
  css_files/model.css
  html_files/Connect4.html
  html_files/_8_Puzzle_game.html
  html_files/checkers_game.html
  html_files/sudoku_game_4x4.html
  html_files/sudoku_game_6x6.html
  index.html
  javascript/checkers_game.js
  javascript/instruction.js
Labels: hard, JWOC

#328 add back to home button
  Block-Buster/index.html
  Block-Buster/styles.css
  HangMan Game/index.html
  HangMan Game/style.css
  Memory Card game/index.html
  Memory Card game/style.css
  Ping_Pong/index.html
  Ping_Pong/style.css
  Rock Paper Scissor/index.html
  Rock Paper Scissor/style.css
  Simon Game/index.html
  Simon Game/styles.css
  Snake Game/index.html
  Snake Game/style.css
  Sorting Visualizer/index.html
  Sorting Visualizer/style.css
  Tic-Tac-Toe/index.html
  Tic-Tac-Toe/style.css
  UNO/css/style.css
  UNO/index.html
  Word Scramble/index.html
  Word Scramble/style.css
  Word/index.html
  Word/style.css
Labels: medium, JWOC

#329 Improved Responsiveness of home page
  css_files/styles.css
  index.html
Labels: hard, JWOC

#326 Added Dino Game
  Dino Game/chrome-dino-game-1200x763-removebg-preview.png
  Dino Game/index.html
  Dino Game/script.js
  Dino Game/style.css
  index.html
Labels: hard, JWOC

#330 Added customised scrollbar to all the games pages
  2048/style.css
  Bingo Game/style.css
  Block-Buster/styles.css
  CrossWord/style.css
  Dino Game/style.css
  HangMan Game/style.css
  Memory Card game/style.css
  Ping_Pong/style.css
  Rock Paper Scissor/style.css
  Rubiks-Cube/style.css
  Simon Game/styles.css
  Snake Game/style.css
  Sudoku_Game_8x8/style.css
  Sudoku_Game_9x9/style.css
  Tetris/style.css
  Tic-Tac-Toe/style.css
  UNO/css/style.css
  Word Scramble/style.css
  Word/style.css
  css_files/_8_Puzzle_game.css
  css_files/checkers_game.css
  css_files/connect4.css
  css_files/sudocu_game_4x4.css
  css_files/sudoku_game_6x6.css
Labels: medium, JWOC
