Repository Spandan-Bhattacharya/Solve_it, pull requests merged in 2024-01, with the labels that each got.

#22 [Fix]: nav bar styling.
  css/styles.css
Labels: easy, JWOC

#26 Stylise the Try Now in button form
  css/styles.css
Labels: easy, JWOC

#27 Sudoku-solver-4x4: Invalid input alert. #7
  README.md
  html/sudoku_solver_4x4.html
  javascript/sudoku_solver4.js
Labels: medium, JWOC

#31 added/scrollbar
  css/styles.css
Labels: easy, JWOC

#28 Added reset button
  html/sudoku_solver_4x4.html
  javascript/sudoku_solver4.js
Labels: easy, JWOC

#36 Add favicon and title #30
  css/styles.css
  favicon.png
  index.html
Labels: medium, JWOC

#41 ADD:Add a Go To Top button
  css/styles.css
  index.html
  javascript/GoToTop.js
Labels: easy, JWOC

#43 Fix Button Click Issue
  css/styles.css
  index.html
Labels: easy, JWOC

#42 Added the search bar
  css/searchstyle.css
  index.html
  javascript/autocomplete.js
Labels: medium, JWOC

#58 UI Fix: #55
  css/styles.css
  html/about.html
Labels: easy, JWOC

#62 Sudoku-Solver-4x4: Improve the visual representation. #9
  assets/bg.webp
  css/sudoku_solver4.css
  html/sudoku_solver_4x4.html
  javascript/sudoku_solver4.js
Labels: hard, JWOC

#69 search bar fix
  javascript/autocomplete.js
Labels: easy, JWOC

#67 Revamped the home screen solver cards
  assets/sudokuback.png
  css/styles.css
  css/sudoku_solver4.css
  html/sudoku_solver_4x4.html
  html/sudoku_solver_6x6.html
  index.html
Labels: hard, JWOC

#86 Social links are added
  index.html
Labels: easy, JWOC

#81 Redesigned the Gototop button
  css_files/styles.css
  html_files/about.html
  html_files/contact.html
  index.html
Labels: easy, JWOC

#91 UI: Background Animation Fixed
  css_files/styles.css
Labels: easy, JWOC

#88 FEAT:Redesigned the about page
  assets/about_bodylogo.png
  css_files/about.css
  html_files/about.html
Labels: medium, JWOC

#89 Search bar fixed
  css_files/searchstyle.css
Labels: medium, JWOC

#102 Implemented 6x6 Sudoku Solver
  css_files/sudoku_solver6.css
  html_files/sudoku_solver_6x6.html
  index.html
  javascript/sudoku_solver6.js
Labels: hard, JWOC

#96 Updated Readme.md file extensively
  README.md
Labels: medium, JWOC

#114 Improved design of the 6x6 sudoku solver.
  css_files/sudoku_solver6.css
  html_files/sudoku_solver_6x6.html
Labels: hard, JWOC

#122 Added 9x9 sudoku solver
  css_files/sudoku_solver9.css
  html_files/sudoku_solver_9x9.html
  index.html
  javascript/sudoku_solver9.js
Labels: hard, JWOC

#136 Different color to the user input cells of sudoku solvers
  .vscode/settings.json
  css_files/sudoku_solver4.css
  css_files/sudoku_solver6.css
  css_files/sudoku_solver9.css
  javascript/sudoku_solver4.js
  javascript/sudoku_solver6.js
  javascript/sudoku_solver9.js
Labels: easy, JWOC

#135 Created a footer for about page
  css_files/Image.png
  css_files/about.css
  html_files/about.html
Labels: medium, JWOC

#143 [ISSUE - 133] Enhance Search Box in the Navbar
  css_files/searchstyle.css
  css_files/styles.css
  index.html
  javascript/autocomplete.js
Labels: hard, JWOC

#151 suggestion section
  css_files/styles.css
  index.html
Labels: medium, JWOC

#158 Added New Contact Us Page
  css_files/newContact.css
  html_files/about.html
  html_files/contact.html
  html_files/contributors.html
  html_files/faq.html
  html_files/newContact.html
  index.html
Labels: hard, JWOC

#163 Update README.md
  README.md
Labels: hard, JWOC

#164 Added Number Solver
  css_files/number_solver.css
  html_files/numbersolver.html
  index.html
  javascript/number_solver.js
Labels: hard, JWOC

#170 added back home button
  css_files/number_solver.css
  html_files/numbersolver.html
Labels: easy, JWOC

#175 added tower of hanoi solution
  css_files/toh.css
  html_files/toh.html
  index.html
  javascript/toh.js
  javascript/toh/game.js
Labels: hard, JWOC

#174 Made About Us Page Responsive
  css_files/about.css
  html_files/about.html
Labels: hard, JWOC

#176 Add icons
  html_files/about.html
  html_files/contributors.html
  html_files/newContact.html
  index.html
  main.js
Labels: easy, JWOC

#178 Reset Button Added
  html_files/numbersolver.html
  javascript/number_solver.js
Labels: medium, JWOC

#181 required changed done on hover effect of contributors page
  css_files/contributors.css
  css_files/styles.css
  javascript/contributors.js
Labels: easy, JWOC

#184 [ISSUE - 180] Improve performance of Word Unscrambler
  css_files/wordsolver.css
  html_files/wordsolver.html
  javascript/wordsolver.js
  javascript/wordsolverDataset/dataset.json
Labels: hard, JWOC
